### ISSUE TITLE
Sobre o Projeto

### ISSUE THREAD

**Issue by gblnovaes** [GabrielVV19/Projeto-Museu-Nacional#1]
Caso precise de Ajuda, cria um task list , para poder ser possível ajudar. 
Se possivel descrever a ideia do projeto.

**Comment by GabrielVV19** [comment]
Não basicamente um projeto mesmo que criei para desenvolver minhas habilidades

**Comment by gblnovaes** [comment]
A agora entendi criou vários repositórios aleatórios para práticar.
